### ISSUE TITLE
Option to disable logging of repos without activity

### ISSUE THREAD

**Issue by thomax** [kamranahmedse/git-standup#105]
I have a lot of repos checked out, but typically only work on a handful at a time. Would be nice to be able to not get dozens upon dozens of
```
/Users/thomas/code/accolade
Seems like Thomas Drevon did nothing!
```
...but only the repos with any activity.

**Comment by kamranahmedse** [comment]
Hey, we already have an option for that. Use `-s` flag to hide the repositories without any activity

```bash
git standup -s
```
