### ISSUE TITLE
Show time of the day

### ISSUE THREAD

**Issue by MartinThoma** [kamranahmedse/git-standup#107]
Sometimes, I forget to note the time when I worked / what I did that day. I use git-standup to see what I did on that day, but I can't see the time.

Could you add the local time like this:

```
8cd361b 08:21 ENH: Added foo feature (13 days ago) <Martin Thoma>
a924f92 12:34 BUG: Fixed bar bug (13 days ago) <Martin Thoma>
e592ccf 17:59 MAINT: Update blub (13 days ago) <Martin Thoma>
```

**Comment by akshayreddy** [comment]
As mentioned in #101, there are several option you can use. 
I think **"git standup -D default"** should be good for your case, unless you wanted exactly like the above format.

**Comment by kamranahmedse** [comment]
Thanks @akshayreddy. @MartinThoma you can use `-D` to provide the date format you need; it will be passed to `--date` flag of the `git log` e.g.

```shell
git standup -D 'format:%H:%m'
```
