### ISSUE TITLE
Add option to check more than one day

### ISSUE THREAD

**Issue by fabienduhamel** [kamranahmedse/git-standup#15]
It should be nice to run:

```sh
$ git-standup -d 3
```

and see what I have done in the last 3 days.

**Comment by neeasade** [comment]
As there are currently options for name and week start/end(which only works if you include both) -- maybe move this to use [http://wiki.bash-hackers.org/howto/getopts_tutorial](http://wiki.bash-hackers.org/howto/getopts_tutorial) ?

`git standup -n "name" -w "SUN-SAT" -d 4` ?

**Comment by kamranahmedse** [comment]
I guess, better would be to use long options i.e.:

```
git standup --name="name" -week="SUN-SAT" --days=4
```

**Comment by neeasade** [comment]
rockin - perhaps instead of days, maybe just allow an option to set the SINCE arg you're passing to the git log command?

**Comment by kamranahmedse** [comment]
Maybe, but I guess days option should be there as itself as well.

**Comment by fabienduhamel** [comment]
Getops should work fine as @neeasade said. It handles long and short options in any order.

```sh
git-standup -n "name" -w "SUN-SAT" -d 4
git standup --name="name" --week="SUN-SAT" --days=4
git standup -n "name" --week="SUN-SAT" -d 4
git standup -d 4
```
should run perfectly. I tried not to broke the code yesterday but it seems that this is the best option. Next try soon.

**Comment by neeasade** [comment]
@fabienduhamel getopts bash builtin does not handle long args. getopt (a shell arg tool present in most linux systems, not OSX) does handle long args ([ref link](http://stackoverflow.com/questions/402377/using-getopts-in-bash-shell-script-to-get-long-and-short-command-line-options)). The most portable option appears to be something like [this](http://mywiki.wooledge.org/BashFAQ/035).

**Comment by fabienduhamel** [comment]
You're right. Thank you for correcting me.

**Comment by kamranahmedse** [comment]
Added the support for that. Now you can do 

```bash
$ git standup -d 5
```
And it will show you what you have done since the last 5 days. Also, other options have been updated, now there are `-a`, `-w` and `-d` flags for author, week and days respectively.

**Comment by fabienduhamel** [comment]
Thank you :+1:

**Comment by nicosomb** [comment]
Hello @kamranahmedse! 

Can you tag a new release with this nice feature (thanks @fabienduhamel for the idea ;-) ) please? 
Then I will publish this new version on homebrew.

**Comment by kamranahmedse** [comment]
Hey @nicosomb 
I forgot to make a release for that. Just created it https://github.com/kamranahmedse/git-standup/releases/tag/2.0.0. Thanks
