### ISSUE TITLE
Group by branches

### ISSUE THREAD

**Issue by n1k0** [kamranahmedse/git-standup#16]
First, this is a great utility.

Right now all commits are listed with no hint of branches they're attached to; would be nice to have an option to group them accordingly.

**Comment by kamranahmedse** [comment]
@n1k0 that is a perfect idea but unfortunately the current implementation is not going to work for that and we will have to change everything, as the current implementation relies heavily on `--pretty` and format specifiers and it doesn't provide anything for the branches except for `%d` and `%D`, which show the branch against the `HEAD` commit only which is not going to be sufficient for this. 

So unfortunately I have to take a pass on this, unless someone is up for the change.
