### ISSUE TITLE
Getting error: "fatal: your current branch 'master' does not have any commits yet"

### ISSUE THREAD

**Issue by jotunskij** [kamranahmedse/git-standup#17]

**Comment by kamranahmedse** [comment]
Duplicate issue https://github.com/kamranahmedse/git-standup/issues/18

**Comment by Hindreen** [comment]
I have the same issue....

**Comment by georgiawang5332** [comment]
your current branch "master" does not have any commits yet??  what can i do ???? i meet big problem...
