### ISSUE TITLE
Error: "fatal: your current branch 'master' does not have any commits yet"

### ISSUE THREAD

**Issue by jotunskij** [kamranahmedse/git-standup#18]
First of all: great tool!

Issue: I'm running git standup in my repository root directory. I get the output from one repository, but then standup fails with:
fatal: your current branch 'master' does not have any commits yet

Any way to debug so I can provide a little more info?

**Comment by kamranahmedse** [comment]
This happens, when you try to get log of an empty repository in git. Will have to fix it. 
Regardless, try making an initial commit and it should work.

**Comment by jotunskij** [comment]
Ok. Once quick fix could perhaps be to print which repository that failed? I have around 50 repos locally cloned and finding which one lacks an initial commit could take some time.

**Comment by jotunskij** [comment]
Added PR #19 to fix this.

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/git-standup/commit/583270b909dc1ba7229f6ee04d2dd33afe8a4563 Thanks 👍

**Comment by manojry996** [comment]
me also get same bug @jotunskij
