### ISSUE TITLE
Doesn't work on Ubuntu 15.10

### ISSUE THREAD

**Issue by povrazor** [kamranahmedse/git-standup#2]
Probably a minor fix. Here's the error.

`/usr/local/bin/git-standup: 11: /usr/local/bin/git-standup: Syntax error: redirection unexpected`

The shell (`/bin/sh`) in Ubuntu is `dash`.

It will work if the first line is changed to:

`#!/bin/bash`

**Comment by kamranahmedse** [comment]
Hey @povrazor 
Did not get the chance to test it anywhere else except my Macbook. Thank you for pointing out, will fix tonight.

**Comment by hschroedl** [comment]
Can confirm both the issue and that the fix proposed by @povrazor works.

**Comment by kamranahmedse** [comment]
Can anyone with ubuntu please verify, if the last update fixed it? @hschroedl @povrazor

**Comment by kamranahmedse** [comment]
Fixed in 3237772b3d441876e71a1e3efe59c7a70fd8d980

**Comment by povrazor** [comment]
Confirmed that 3237772 does fix it.
