### ISSUE TITLE
question: what does `[[ -t 1 ]]` check?

### ISSUE THREAD

**Issue by sarbbottam** [kamranahmedse/git-standup#25]
Please excuse my bash-fu, but what does `if [[ -t 1 ]]` check in `if [[ -t 1 ]] && [[ -n "$ncolors" ]] && [[ "$ncolors" -ge 8 ]] ; then;` 

Thanks!

**Comment by kamranahmedse** [comment]
`-t 1` to check if stdout is a terminal

**Comment by sarbbottam** [comment]
Thanks!
