### ISSUE TITLE
How to show standup info for everyone at once?

### ISSUE THREAD

**Issue by markogresak** [kamranahmedse/git-standup#28]
Looking at the readme, I can't find an option where I could see standup info for everyone at once. There are multiple members in the repo and I'd like to check what everyone was doing, at once. Is this possible with current version? If not, could it be considered as a new feature?

**Comment by kamranahmedse** [comment]
Bummer! We don't have that yet. But seems to be a minor thing. Will add it.

**Comment by DanyC97** [comment]
@kamranahmedse nice idea :+1:  will love having this implemented

**Comment by kamranahmedse** [comment]
Added. Now you can do `git standup -a all` and check what everyone did.
Thanks for locking the issue.
