### ISSUE TITLE
Support querying 'full' sub directories 

### ISSUE THREAD

**Issue by lukech** [kamranahmedse/git-standup#29]
While practicing I realized it supported queries for only a single level of sub directory - some of git repos enclosed deeper in my current directory could not be queried out. Would be handy to add 'full' sub directory query support as a new feature.

**Comment by bitboxer** [comment]
I am working in an agency and have the following directory structure:

```
|-Company1
|   |
|   |- Project A
|   \ Project B
\-Company2
    |
    |- Project A
   \ Project B
```

I would love to to a `git standup` in the root dir and see all the stuff I did for all of those companies.

**Comment by kamranahmedse** [comment]
There was a similar request before https://github.com/kamranahmedse/git-standup/issues/5.

Unfortunately, I do not agree with this as adding this will add un-necessary complexity and will pollute the code rather than adding much value.

**Comment by bitboxer** [comment]
Sad to hear. Will fork and implement it myself then. If you want I can create a PR for that.

**Comment by kamranahmedse** [comment]
No promises, but if you do it then okay create a PR. We will see. :)
