### ISSUE TITLE
Install on Windows?

### ISSUE THREAD

**Issue by gaui** [kamranahmedse/git-standup#3]
How would you install this on Windows?

**Comment by ivanstegic** [comment]
Would [bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) make this possible?

**Comment by neeasade** [comment]
This is a shell script -- as long it's in your %PATH% you would be able to run this from a git bash shell.

**Comment by apjanke** [comment]
With #37 merged, there's no longer a need to comment out those lines. Systems without `tput` are detected and handled gracefully now.

If you're running Cygwin or MSYS, I bet this will work as is now, at least under those bash environments.

**Comment by martincostello** [comment]
I use Windows, I just went down the ```npm install -g git-standup``` route and it works as expected as far as I can tell.

**Comment by kamranahmedse** [comment]
Yes, ideally it should work but I have been waiting to test it myself, before closing, as soon as I get a hold of Windows :)

**Comment by afnpires** [comment]
@martincostello Out of curiosity what windows shell did you use? Powershell, Bash on windows?

I tired on cmd and Powershell with no luck 😞

**Comment by martincostello** [comment]
@afnpires I just use PowerShell, but I tried cmd just and that was fine for me too.

**Comment by afnpires** [comment]
@martincostello strangely for me always returns an empty result.

I'll post in this thread if I figure the solution for my problem.

**Comment by GuilhermeHideki** [comment]
I just want to point out that I needed to put find from linux before the Windows version in the %PATH% resolution.

@afnpires Maybe you need to specify the depth of search (with the -m parameter)

**Comment by kamranahmedse** [comment]
Just tested on windows and it works out of the box without any setup. Closing it for being non-issue.
