### ISSUE TITLE
Allow different date output

### ISSUE THREAD

**Issue by alexanderadam** [kamranahmedse/git-standup#39]
`git-standup` works fine for standup data but if you want a summary for things that are longer in the past a proper date value would be better.

Perhaps as an option (i.e. optional `%ci` formatting instead `%cr`).

Thank you very much and have a nice day!

**Comment by md5** [comment]
I opened a PR for this at #45 

To do the equivalent of `%ci`, you would do this:

> git standup -D iso

**Comment by kamranahmedse** [comment]
Added in https://github.com/kamranahmedse/git-standup/issues/45 Thanks to @md5 👍
