### ISSUE TITLE
Problems when piping output

### ISSUE THREAD

**Issue by goerge** [kamranahmedse/git-standup#44]
When piping git standups output to less or a file it always says 
_Seems like ... did nothing!_

![git-standup-does-not-work-with-less](https://cloud.githubusercontent.com/assets/617230/15268819/0f9fa3ec-19ec-11e6-8bb7-986c6a54c0ce.gif)

**Comment by md5** [comment]
The conditional here is wrong: https://github.com/kamranahmedse/git-standup/blob/master/git-standup#L48

It looks like the intent was to provide an uncolored output format if there is no terminal, but the whole thing is wrapped in the `if` block, which results in an empty format string.

**Comment by kamranahmedse** [comment]
@goerge it should be fixed now.

**Comment by goerge** [comment]
Cool. Works like a charm. Thanks!
