### ISSUE TITLE
Specify directory

### ISSUE THREAD

**Issue by drodil** [kamranahmedse/git-standup#49]
It would be nice to have possibility to define directory where to check for commits from. I am planning to create small cron job that would convert the output to an HTML page so everyone could see what others did yesterday but now I need some bash magic to get that to work.

**Comment by kamranahmedse** [comment]
Get into that directory and run the command?!

**Comment by OmgImAlexis** [comment]
When using this programmatically it'd be nice to be able to specify a directory name as the first param. For example [tiny-care-terminal](https://github.com/notwaldorf/tiny-care-terminal/blob/0e7d6ae65953bc8348406f65b70d0bbe60a1e384/standup-helper.sh).
