### ISSUE TITLE
Multiple Git Repositories

### ISSUE THREAD

**Issue by lubos-bistak** [kamranahmedse/git-standup#5]
Multiple Git repositories? 

... is it possible to extend the script to scan all sub-directories to automatically search for Git repos and execute this very nice command / tool there?

**Comment by kamranahmedse** [comment]
The functionality is already there. Have a look at the readme

> Open a directory having multiple repositories and run

https://github.com/kamranahmedse/git-standup#multiple-repository-usage

**Comment by lubos-bistak** [comment]
It only works, if the directory contains other Git Repos directly inside, but following doesn't work:

groups/
.../group-A
.../group-B

... and ...

group-A/
.../git-repo-1
.../git-repo-2
group-B/
.../git-repo-3
.../git-repo-4

It is possible to support also this situation? :)

**Comment by fabienduhamel** [comment]
IMO it would do a lot of useless checks in vendor or library code with a deep folder structure that you doesn't want to go.
