### ISSUE TITLE
Incoherent results

### ISSUE THREAD

**Issue by mrbacay** [kamranahmedse/git-standup#50]
When I do `git standup`, it tells me that I "did nothing." But when I pass a day parameter like `git standup -d 2`, it returns a commit I made 29 hours ago. I used Homebrew for installation.

**Comment by kamranahmedse** [comment]
Yeah because 
```
29 hours = 24 hours + 5 hours
``` 
i.e. the commit that you made the day before yesterday. ;-)

**Comment by mrbacay** [comment]
Oops…thanks for pointing that out 😁
