### ISSUE TITLE
-m flag for Directory depth is not working

### ISSUE THREAD

**Issue by zeke** [kamranahmedse/git-standup#53]
It seems the `-m` flag is not working. Maybe because my home directory is itself a git repo?

```
~
❯ git standup -m 3
Seems like Zeke Sikelianos did nothing!

~
❯ cd zeke 

~/zeke
❯ git standup
/Users/zeke/zeke/count-array-values
a3f45c8 - more node 0.10 backporting (12 hours ago) <Zeke Sikelianos>
fff3927 - node 0.10 :sigh: (12 hours ago) <Zeke Sikelianos>
e8a9be8 - use var (12 hours ago) <Zeke Sikelianos>
88863a3 - add travis (12 hours ago) <Zeke Sikelianos>
8611c1a - it's alive (12 hours ago) <Zeke Sikelianos>
/Users/zeke/zeke/electron-universe
043e2b6 - stuff (22 hours ago) <Zeke Sikelianos>
/Users/zeke/zeke/nice-package
c07f909 - 1.2.1 (21 minutes ago) <Zeke Sikelianos>
```

**Comment by jonnymaceachern** [comment]
In my case, there was a git repo initialized in the root directory that contained all my projects (the directory I was running `git standup` from). Removing that repo solved this issue.

**Comment by kamranahmedse** [comment]
@zeke this has been fixed in the latest release. 

I am sorry that it took me 3 years to revisit this issue. `git-standup` stops on the first occurrence of the git repository. In your can use `-F` flag to force the recursion to the given depth:

```shell
git standup -m 3 -F
```

**Comment by zeke** [comment]
Thanks for the followup! ✨
