### ISSUE TITLE
Allow custom date ranges

### ISSUE THREAD

**Issue by nickel715** [kamranahmedse/git-standup#54]
Very handy tool, especially run on multiple repositories is very awesome!

It would be nice to have the option to show the logs for a specific date, e.g. for last week monday.

Maybe the easiest solution is passingthrough this git log options:

       --since=<date>, --after=<date>
           Show commits more recent than a specific date.

       --until=<date>, --before=<date>
           Show commits older than a specific date.

**Comment by epeli** [comment]
See https://github.com/kamranahmedse/git-standup/pull/94
