### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by austin-thesing** [kamranahmedse/git-standup#61]
I keep getting this issue when I try to run the plugin on MacOS Sierra. It appears to have installed correctly. I tried a sudo install too.

`find: ./.gnupg: Permission denied`

**Comment by m4grio** [comment]
I don't think it has nothing to do with `git-standup`. Seems like you've used `sudo` to do something with your GPG Keys.
Have you tried to restore permissions? Everything under your `$HOME` should be _yours_.
