### ISSUE TITLE
Run in repo sub-directory

### ISSUE THREAD

**Issue by zhulik** [kamranahmedse/git-standup#64]
When I run `git standup` in sub-directory of my repos it shows nothing(no commits or error message), although all default git commands work fine

**Comment by malachid** [comment]
I ran into the same thing. It falls through the bottom of the script and exits with exit code 0.
It's because of this part:
`    ## Show the detail only if it is a git repository`
`    if [[ -d ".git" || -f ".git" ]] ; then`

**Comment by dgarrick** [comment]
I believe I have a solution for this. If possible, I'd like to mess with it over the weekend and see if I can come up with a PR.

**Comment by jb08** [comment]
@dgarrick great! push the change to your local forked git-standup, then make a PR to this upstream repo. nice job

**Comment by dgarrick** [comment]
@jb08 I considered doing so, but it seems that there are a lot of good PR's just sitting around in this repo. I would still need to clean up my changes before submitting, so I don't feel particularly motivated to do so.

This is by no means a knock against the maintainer/author -- this repo became very popular, especially for a small command-line utility, and I can imagine it would be hard to manage.

**Comment by kamranahmedse** [comment]
Hey @dgarrick, sorry! I am not getting much time. Will try to clean up the PRs by this coming weekend. Thanks for the reminder :)

**Comment by dgarrick** [comment]
@kamranahmedse no worries! Thanks for putting this tool out in the open. I'll try to submit my PR once I get a little time as well 👍

**Comment by kamranahmedse** [comment]
Fixed in #86. Thanks guys
