### ISSUE TITLE
Missing option when installed with homebrew

### ISSUE THREAD

**Issue by tristanbes** [kamranahmedse/git-standup#66]
homebrew package installed doesn't have `-f` option. 

Yet it shows that it installed the version `git-standup/2.1.8`

Installing it with curl fixed the problem.

**Comment by p-j** [comment]
Same problem with yarn/npm install.
`-f` is not among the valid flag

**Comment by kamranahmedse** [comment]
Looks like I forgot to publish them properly. Will do, thanks for reporting.

**Comment by TheKevJames** [comment]
Confirmed this is solved with the latest homebrew package version.

**Comment by kamranahmedse** [comment]
Thanks @TheKevJames
