### ISSUE TITLE
Feature Request: Show the git history for a specific day

### ISSUE THREAD

**Issue by JimFung** [kamranahmedse/git-standup#70]
It would be helpful to be able to not show all the commits from n days ago but to show the commits from a day, n days in the past.

For example, 
```
git standup -D 5
```
could show all the commits you made for the day, 5 days ago.

**Comment by oxyc** [comment]
Desperately need this for when I'm weeks behind on logging work hours 😄

**Comment by kamranahmedse** [comment]
Hey, thanks for opening the issue but you can already do that using a mix of `u` and `d` flags

```
  -u      - Specify the number of days back until this day
  -d      - Specify the number of days back to include
```

For example if you want the log for 5th day from today, you can translate it to `git standup from 5 days ago till 4 days ago`

```
git standup -d 5 -u 4
```

![image](https://user-images.githubusercontent.com/4921183/35913618-908ef5c2-0c00-11e8-8848-af60d2b8c54f.png)

Hope it helps
