### ISSUE TITLE
Issue with username with non-ASCII chars

### ISSUE THREAD

**Issue by elMestre** [kamranahmedse/git-standup#73]
> Quick tip if if you Google to here:
> This can be workarounded using the flag *`-a "all"`*

Hi there,

Thanks for what you did here, is amazing :)

It would seem that if user has strange characters like `áéíóúàèìòù` (but maybe many others), git standup will not detect the commits properly, throwing the message:

`
Seems like úsérnámé did nothing!
`

Best regards

**Comment by kamranahmedse** [comment]
Hey :)

Git standup just proxies the author to `git log` so it could be from `git log`. Could you please try below and see if it works? 
```
git log --author=úsérnámé
```
Otherwise you may use the email
```
git standup --author="you@email.com"
```
