### ISSUE TITLE
Feature request: Visualize data in console

### ISSUE THREAD

**Issue by iegik** [kamranahmedse/git-standup#76]
How can I visualize output for a week or month?

![2017-05-12 12 47 21](https://cloud.githubusercontent.com/assets/175293/25993006/39c4245c-3711-11e7-8ee7-600c2e89c129.png)

Can I customize output format (or pass git-log custom arguments to git standup)?

**Comment by kamranahmedse** [comment]
Hey @iegik thanks for opening the issue; this is way out of the scope of git-standup and I don't think it is ever going to support this.
