### ISSUE TITLE
line 37: cd: */: No such file or directory

### ISSUE THREAD

**Issue by loretoparisi** [kamranahmedse/git-standup#8]
```shell
macbookproloreto:metadata admin$ git standup
/usr/local/bin/git-standup: line 37: cd: */: No such file or directory
macbookproloreto:metadata admin$ vi /usr/local/bin/git-standup:37
```

**Comment by kamranahmedse** [comment]
Unable to reproduce this. Could you please provide a bit of the details about your environment?

**Comment by loretoparisi** [comment]
It's `MacOS X 10.10.5`

**Comment by kamranahmedse** [comment]
I have the same version and it is working fine. It could be some permissions issue or anything. Could you may be uninstall it and try to reinstall if that helps?

**Comment by kamranahmedse** [comment]
@loretoparisi did it work?

**Comment by loretoparisi** [comment]
nope. will try again.
