### ISSUE TITLE
ignoring certain folder patterns?

### ISSUE THREAD

**Issue by Madd0g** [kamranahmedse/git-standup#89]
It takes a long time to get a report because I have multiple levels of code folders but also many node projects on 1st level, so it spends a lot of time going over node_modules, where I will never have my own git repos.

Any way to exclude certain folders?

**Comment by kamranahmedse** [comment]
[Just add `.git-standup-whitelist` file to the directory](https://github.com/kamranahmedse/git-standup#directory-whitelisting) where you run the standup from mentioning the directories that it should look into.
