### ISSUE TITLE
Option to use AuthorDate instead of CommitDate

### ISSUE THREAD

**Issue by L3viathan** [kamranahmedse/git-standup#92]
When I rebase branches, git-standup shows me all the rebased commits. While this is in a sense correct, it is not always useful. For this usecase, a switch would be good that makes git-standup look at the AuthorDate (when the commit was originally authored) rather than the CommitDate (when the commit was made).

**Comment by kzap** [comment]
+1 here I want authordate and not commit date since I want to know what I worked on during those days and not when it was merged/committed into the branch.

It should be AuthorDate by default imo

**Comment by kzap** [comment]
Made a PR for this in #97 :)

**Comment by kamranahmedse** [comment]
Thanks @kzap
