### ISSUE TITLE
Does not work at user home level if the user directory itself is a Git repository as well

### ISSUE THREAD

**Issue by vanniktech** [kamranahmedse/git-standup#96]
My user home directory `~` is a Git Repository https://github.com/vanniktech/config-home
I ignore everything except a few dot files and some directories. 

Inside `~/dev/` I've got all of my other Git projects. Running inside `~/dev/` works fine but when running inside `~` git standup does not work corectly and says I've done nothing.

Would it be possible to still go the directory depth down even if the directory that you are currently in is a git repository?

**Comment by zoellner** [comment]
same problem when using it on a git repo with multiple submodules. 
I'd suggest that explicitly adding an option similar to `-m` that will go through the directories regardless of whether it found something or not
